export const ALL_STAKE_HOLDERS = 'ALL_STAKE_HOLDERS';
export const DASH_BOARD = 'DASH_BOARD';
export const MANAGE_STAKE_HOLDERS = 'MANAGE_STAKE_HOLDERS';
export const FEED_BACK_PORTAL = 'FEED_BACK_PORTAL'
